kubeProxyReplacement: true
routingMode: native
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 10.42.0.0/16
autoDirectNodeRoutes: true

dashboards:
  enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

loadBalancer:
  mode: dsr # 전역 기본은 SNAT
  acceleration: disabled # XDP 가속설정

bpf:
  masquerade: true
  lbModeAnnotation: true # 서비스별 DSR/SNAT 오버라이드 활성화

enableIPv4Masquerade: true
enableIPv6Masquerade: false

externalIPs:
  enabled: true

nodePort:
  enabled: true

operator:
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true

rollOutCiliumPods: true

# 한노드 부하 때문에 BGP로 대체
#k8sClientRateLimit:
#  qps: 10 # 계산 공식 QPS = (#service) * (1 / leaseRenewDeadline) | 기본값 10
#  burst: 20 # QPS 보다 약간 높게 | 기본값 20
# failover 시간 : (leaseDuration - leaseRenewDeadline) - (leaseDuration + leaseRenewDeadline)
l2announcements:
  enabled: false
#  leaseDuration: 15s # lease 만료 시간(리더 다운) | 기본값 15s
#  leaseRetryPeriod: 2s # lease 갱신 실패 시 대기 시간 | 기본값 2s
#  leaseRenewDeadline: 5s # lease 갱신 주기 | 기본값 5s

bgp: # 레거시 제거
  enabled: false
bgpControlPlane:
  enabled: true

# gateway api 로 대체
ingressController:
  enabled: false
  default: true
  loadbalancerMode: shared
  hostNetwork:
    enable: false

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true # GEP-1911
  hostNetwork:
    enabled: false

envoy:
  enabled: true
  nodeSelector:
    web.gateway/node-pool: "envoy"
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  #securityContext: # hostnetwork 사용시
  #  capabilities:
  #    keepCapNetBindService: true
  #    envoy:
  #      - NET_BIND_SERVICE
  #      - NET_ADMIN
  #      - SYS_ADMIN

hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction"
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  #relay:
  #  enabled: true
  #  rollOutPods: true
  #ui:
  #  enabled: true
  #  rollOutPods: true
  #  service:
  #    type: ClusterIP

# kube-proxy-free API VIP
k8sServiceHost: 172.16.0.11
k8sServicePort: 6443
