---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBUs6NGjTYWxKjclOkWCL1TFw/pO3wnxQfysiiHftB3NfzvwkJFQ7u6jQP5kNirkXbevzV2hQCouYtc9nMvVYlW2Va6N4jdftTy5nNaoAenF2uD/yINmD/Q1U9jL8Zx+EeYU8jJCxXt2Li4hhhsc5XC958FQsnmFhC3Puq1ry23DLXUUatxiwsJYMvfdOfLQ/rxOanUiz5pSEPKnvEZpPb1O/bCkF/btG9FIQAtsZvZa0zMc9VXojXZxT58hpv3pqXV66ZL8yJdWxjNc3wAJtjxBwCQ0x+KKAFGfvWj+MYBwGX9W3Lesviti1CYQmxOs17HAFh1bQcGYiMAi/VXwR0FnfrrlZf0w+oGKDhBwvDZH6htEXbqmOz7l6Eu6drlxl/hmEC6IJ3BaaPYjsY6QtieNgTPF1UtTzGRJL9UhwSE77pk59QzApPnJYMlJwjzGL2OMKHRmxQzcD5tlbtBq935UAnL3W7A3byVRbzblq3KqhbI/QuBOem4CqReLSDULM8m3n6yLjl+gTWCO0axqT6tmgwlEj04s8LxXCu8A8n5U7+nnRTSGayqRw83krebpLWkwLRGSQqNG4vjAZzkCaOh4r6A07oKZJy5+8Og9ULjegC/V/x+8/aUFTdyYfu0Kdh3ECakOhHl1P9lkp/B/CMbvACP9znrdH4ggSo8eqKA7JGl1rj1MkR5oqU7o9xLPEEwfLnet390kZpw+Om1Bd1j8UnS/NpvrRWN4KbsKXNmAhiHwIKDZ+Er
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
