apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: 0.53.0
    releaseName: fluent-bit
    namespace: monitoring
    includeCRDs: true
    valuesFile: values.yaml
