apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.40.0
    releaseName: loki
    namespace: monitoring
    includeCRDs: true
    valuesFile: values.yaml
