apiVersion: apps/v1
kind: Deployment
metadata:
  name: wooco-spring
  namespace: wooco-spring
spec:
  replicas: 3
  revisionHistoryLimit: 2
  template:
    spec:
      nodeSelector:
        wooco.kr/node-pool: "web"
      containers:
        - name: spring
          image: hongserver/wooco-be:v1.0.1
          resources:
            requests:
              cpu: "1000m"
              memory: "2048Mi"
            limits:
              cpu: "2000m"
              memory: "2560Mi"
          envFrom:
            - secretRef:
                name: wooco-prod-env
