apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wooco-spring

resources:
  - ../../base
  - sealed-secrets.yaml

patches:
  - path: deployment.yaml
  - path: http-route.yaml
  - path: servicemonitor.yaml
  - path: sealed-secrets.yaml
  - path: pdb.yaml

labels:
  - includeSelectors: true
    pairs:
      environment: prod
