apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wooco-spring
  namespace: wooco-spring
spec:
  selector:
    matchLabels:
      environment: prod
  targetLabels:
    - environment
