apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: wooco-mysql
  namespace: mysql
  # labels:
  #   app.kubernetes.io/name: wooco-mysql
spec:
  instances: 3

  tlsUseSelfSigned: true
  secretName: mysql-root-secret
  serviceAccountName: wooco-mysql-sa

  datadirVolumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: local-path-retain
    resources:
      requests:
        storage: 5Gi

  podSpec:
    nodeSelector:
      database.mysql: "true"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: mysql.oracle.com/component
                  operator: In
                  values: ["server"]
            topologyKey: "kubernetes.io/hostname"
    containers:
      - name: mysql
        resources:
          requests:
            cpu: "1000m"
            memory: "2048Mi"
          limits:
            cpu: "2000m"
            memory: "4096Mi"

  router:
    instances: 2
    podSpec:
      nodeSelector:
        database.mysql-router: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: mysql.oracle.com/component
                    operator: In
                    values: ["router"]
              topologyKey: "kubernetes.io/hostname"
      # containers:
      #   - name: router
      #     resources:
      #       requests:
      #         cpu: "250m"
      #         memory: "512Mi"
      #       limits:
      #         cpu: "500m"
      #         memory: "1024Mi"

  service:
    defaultPort: mysql-rw

  mycnf: |
    [mysqld]
    innodb_buffer_pool_size=500M
    innodb_buffer_pool_instances=2

    max_connections=300
    tmp_table_size=64M
    max_heap_table_size=64M

    innodb_log_file_size=512M
