apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: wooco-mysql-cluster
  namespace: mysql-cluster
spec:
  instances: 3

  tlsUseSelfSigned: true
  secretName: wooco-mysql-cluster-secret
  serviceAccountName: wooco-mysql-cluster-sa

  datadirVolumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: local-path-retain
    resources:
      requests:
        storage: 30Gi

  podSpec:
    nodeSelector:
      database.mysql-cluster: "true"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: mysql.oracle.com/component
                  operator: In
                  values: ["server"]
            topologyKey: "kubernetes.io/hostname"
    containers:
      - name: mysql
        resources:
          requests:
            cpu: "1000m"
            memory: "2048Mi"
          limits:
            cpu: "2000m"
            memory: "4096Mi"

  mycnf: |
    [mysqld]
    innodb_buffer_pool_size=1024M
    innodb_buffer_pool_instances=2
    max_connections=300
    tmp_table_size=64M
    max_heap_table_size=64M
    innodb_log_file_size=256M

  metrics:
    enable: true
    image: prom/mysqld-exporter:v0.17.2
    options:
      - "--web.listen-address=:9104"
      - "--mysqld.address=127.0.0.1:3306"
      - "--mysqld.username=exporter"
      - "--collect.info_schema.innodb_metrics"
      - "--collect.info_schema.processlist"
      - "--collect.perf_schema.replication_group_members"
      - "--collect.perf_schema.replication_group_member_stats"
    monitor: true
    # monitorSpec:

  router:
    instances: 2

    podSpec:
      nodeSelector:
        database.mysql-cluster: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: mysql.oracle.com/component
                    operator: In
                    values: ["router"]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: router
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
