apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealed-secrets.yaml
  - innodbcluster.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - limitrange.yaml

helmCharts:
  - name: mysql-operator
    repo: https://mysql.github.io/mysql-operator
    version: 2.1.8
    releaseName: mysql-operator
    namespace: mysql-operator
    includeCRDs: true
    valuesFile: values.yaml
