apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac-innodb-sidecar.yaml

helmCharts:
  - name: mysql-operator
    repo: https://mysql.github.io/mysql-operator
    version: 2.1.8
    releaseName: mysql-operator
    namespace: mysql-operator
    includeCRDs: true
    valuesInline:
      replicas: 1
      envs:
        k8sClusterDomain: "cluster.local"

  - name: mysql-innodbcluster
    repo: https://mysql.github.io/mysql-operator
    version: 2.1.8
    releaseName: wooco-mysql-cluster
    namespace: mysql-cluster
    includeCRDs: false
    valuesFile: values.yaml
