apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway-class.yaml
  - gateway-external.yaml
  - gateway-internal.yaml
  - wildcard-cert.yaml

generatorOptions:
  disableNameSuffixHash: true
