apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valkey-sentinel

resources:
  - namespace.yaml

helmCharts:
  - name: redis-ha
    repo: https://dandydeveloper.github.io/charts
    version: 4.33.8
    releaseName: wooco-valkey-sentinel
    namespace: valkey-sentinel
    includeCRDs: true
    valuesFile: values.yaml
